name: auto_category_labeling
on:
  issues:
    types: [opened, labeled, unlabeled]
  push:

jobs:
  labeling:
    runs-on: ubuntu-latest
    steps:
      - name: remove pikachu if pokemon except pikachu
        uses: actions/github-script@v3
        if: >-
          contains(github.event.issue.labels.*.name, 'pokemon/pikachu')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            issue = await github.issues.get({
              owner: context.issue.owner,
              repo: context.issue.repo,
              issue_number: context.issue.number,
            });

            count = (
              issue.data.labels
                .map((label) => label.name)
                .join(',')
                .match(/pokemon\//g) || []
            ).length;
            if (count >= 2) {
              github.issues.removeLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['pokemon/pikachu']
              });
            }
      - name: add pikachu if no pokemon
        uses: actions/github-script@v3
        if: >-
          ! contains(github.event.issue.labels.*.name, 'pokemon/')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['pokemon/pikachu']
            });
