name: draw Yu-Gi-Oh! card
on:
  issue_comment:
    types: [created, edited]

jobs:
  draw:
    runs-on: ubuntu-latest
    steps:
      - name: draw Yu-Gi-Oh! card on issue
        uses: satackey/action-js-inline@release-master
        if: >-
          contains(github.event.comment.body, 'draw')
          || contains(github.event.comment.body, 'ドロー')
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            let request = new XMLHttpRequest();
            const URL = "https://db.ygoprodeck.com/api/v7/randomcard.php";

            request.open("GET", URL);
            request.send();
            request.onload = () => {
              if (request.status === 200) {
                console.log(JSON.parse(request.response));
                const cardName = responce.name;
                const imageUrl = responce.card_images[0].image_url;

                github.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: `_**Draw! "\"${cardName}"\" !!**_\n![${cardName}](${imageUrl})`,
                });
              } else {
                console.log(`error: ${request.status} ${request.statusText}`);
              }
            };
