name: 'GitHub Actions Playground'
on:
  issues:
    types: [labeled]

jobs:
  automate-github-project:
    runs-on: ubuntu-latest
    steps:
      - name: 
        uses: alex-page/github-project-automation-plus@v0.6.0
        if: >-
          contains(github.event.issue.labels.*.name, 'barcelona')
        with:
          project: Playground
          column: To do
          action: update
          repo-token: ${{ secrets.GITHUB_TOKEN }}
