name: 'GitHub Actions Playground'
on:
  issues:
    types: [labeled]

jobs:
  automate-github-project:
    runs-on: ubuntu-latest
    steps:
      - name: 
        uses: Doarakko/github-project-automation-plus@main
        if: >-
          contains(github.event.issue.labels.*.name, 'barcelona')
        with:
          project: GitHub Actions Playground
          column: To do
          action: add
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
