name: 'GitHub Actions Playground'
on:
  issues:
    types: [assigned]

jobs:
  automate-github-project:
    runs-on: ubuntu-latest
    steps:
      - name: 
        uses: alex-page/github-project-automation-plus@v0.7.1
        if: >-
          contains(github.event.issue.assignees.*.login, 'Doarakko')
        with:
          project: GitHub Actions Playground
          column: To do
          repo-token: ${{ secrets.GHPROJECT_TOKEN }}
